### ISSUE TITLE
Create UI for the User Registration Form

### ISSUE THREAD

**Issue by hound77** [chiraag-kakar/createnshare#27]
Registration Form 
* responsive
* fields : username, email, password, password confirmation => Register Button

**Comment by sahilkr9** [comment]
I want to work on this issue

**Comment by Rik-21** [comment]
i want on work on this issue under JWoC

**Comment by SaarthakMaini** [comment]
@hound77 I would like to work on this issue under JWOC.  Please assign this to me. Thank you!!

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC.
