### ISSUE TITLE
Create UI for the Login Page

### ISSUE THREAD

**Issue by hound77** [chiraag-kakar/createnshare#30]
Login Page Preview
* username 
* password
* Login Button
* Forgot Password Button
* Captcha Implementation

**Comment by riiyaaa** [comment]
I would like to work on it under jwoc

**Comment by ishikaagarwal25** [comment]
I want to work on this issue under JWOC

**Comment by Rik-21** [comment]
i Want to work on the issue under JWoC

**Comment by SaarthakMaini** [comment]
@hound77 I would like to work on this project. Can you please assign this to me? Thank you!!

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC.
