### ISSUE TITLE
Create Home View Page

### ISSUE THREAD

**Issue by hound77** [chiraag-kakar/createnshare#32]
DashBoard which will be available for users after login
* Logout Button
* Welcome message

**Comment by riiyaaa** [comment]
I would like to work on this issue.

**Comment by riiyaaa** [comment]
> I would like to work on this issue.

(under JWOC)

**Comment by SaarthakMaini** [comment]
@hound77 I would love to work on this issue. Please assign it to me! Thank you!!

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC.
