### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by hound77** [chiraag-kakar/createnshare#34]
As of now, we are extending Django's User class defined in django.contrib.auth
If you want to use AbstractUser class then you will face issues while migrating the DB and the issue is not resolved (needs help)

Error message:-
" django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency app.0001_initial on database 'default' "

**Comment by belelaritra** [comment]
I want to work on this issue under JWOC.

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC.
