### ISSUE TITLE
Create UI for Forgot Password Page

### ISSUE THREAD

**Issue by hound77** [chiraag-kakar/createnshare#35]
* Email Input Field will be there
* Send OTP button
* 
![WhatsApp Image 2022-02-04 at 02 02 03](https://user-images.githubusercontent.com/50631450/152424169-cfeb3f56-ff08-4965-8e36-9d11e6759e38.jpeg )

**Comment by sahilkr9** [comment]
I want to work on this issue

**Comment by ishikaagarwal25** [comment]
I want to work on this issue

**Comment by SaarthakMaini** [comment]
@hound77 I would like to work on this issue. Please assign it to me. Thank you!!

**Comment by Shruti025** [comment]
hey can I work on this issue under JWOC?

**Comment by tanya-gupta25** [comment]
I want to work on this issue under JWOC.

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC.

**Comment by riiyaaa** [comment]
I would like to work on it under JWOC
