### ISSUE TITLE
User Account Activation page

### ISSUE THREAD

**Issue by hound77** [chiraag-kakar/createnshare#36]
Create a user account activation page which will be created if the user clicks the account activation link which will be sent to their email id
Message to be shown:-
"Your account has been activated successfully"

**Comment by belelaritra** [comment]
I want to work on this issue under JWOC.

**Comment by ishikaagarwal25** [comment]
I want to work on this issue under JWOC

**Comment by das-ankur** [comment]
I want to work on this issue under JWOC

**Comment by shlokjjw** [comment]
I want to work on this issue under JWOC
